#!/bin/sh
echo 1 > /proc/sys/net/ipv4/ip_forward

iptables -A INPUT -i lo -j ACCEPT

iptables -A FORWARD -i enp1s0 -o enp3s1 -j ACCEPT
iptables -t nat -A POSTROUTING -o enp3s1 -s 192.168.0.0/16 -j MASQUERADE 
iptables -A FORWARD -i enp3s1 -m state --state ESTABLISHED,RELATED -j ACCEPT
iptables -A FORWARD -i enp3s1 -o enp1s0 -j REJECT
